name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read   # 如果是私有子模块需要改为 write
      pages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 添加此项确保完整检出历史

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: npm install
      - run: npm run build

      # 增加目录验证步骤
      - name: List files
        run: ls -R ./dist

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - uses: actions/deploy-pages@v3